on:
  workflow_dispatch:
    inputs:
      pkg_name:
        description: 'The package to publish'
        required: true
        type: choice
        options:
          - LaunchDarkly.ClientSdk
          - LaunchDarkly.ServerSdk
          - LaunchDarkly.ServerSdk.Telemetry

name: Publish Docs
jobs:
  build-publish:
    runs-on: macos-latest
    permissions:
      contents: write # Needed in this case to write github pages.
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-env
        with:
          workspace_path: ${{ inputs.pkg_name }}

      - id: build
        name: Build and Test SDK
        uses: ./.github/actions/ci
        with:
          project_file: ${{ env.PROJECT_FILE }}
          test_project_file: ${{ env.TEST_PROJECT_FILE }}

      - id: build-docs
        name: Build Documentation
        uses: ./.github/actions/build-docs
        with:
          workspace_path: ${{ env.WORKSPACE_PATH }}

      - id: publish-docs
        name: Publish Documentation
        uses: ./.github/actions/publish-docs
        with:
          workspace_path: ${{ env.WORKSPACE_PATH }}
          token: ${{secrets.GITHUB_TOKEN}}
