name: LaunchDarkly.ServerSdk.Telemetry CI
on:
  push:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md' # Do not need to run CI for markdown changes.
  pull_request:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md'

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-env
        with:
          pkg_name: LaunchDarkly.ServerSdk

      - uses: launchdarkly/gh-actions/actions/release-secrets@release-secrets-v1.0.1
        name: Get secrets
        with:
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}

      - uses: ./.github/actions/ci
        with:
          project_file: ${{ env.PROJECT_FILE}}
          test_project_file: ${{ env.TEST_PROJECT_FILE}}

      - uses: ./.github/actions/build-docs
        with:
          workspace_path: ${{ env.WORKSPACE_PATH}}
